#!/bin/bash

echo 'Remove Containers'

# Specify the name of your Docker container
container_name="db"
 
# Check if the container exists
if docker ps -a --format '{{.Names}}' | grep -q "$container_name"; then
    echo "Container $container_name exists."
    docker rm -f db
fi

echo "Building.."
docker compose build
	
echo "Testing.."
dotnet restore /gitrepo/src/Server/Server.csproj

echo 'Docker container down'
docker compose down

echo 'Docker container up'
docker compose up -d

exit
