#!/bin/bash

echo 'Remove Containers'
docker rm -f db
docker rm -f web


echo "Building.."
docker compose build
	
echo "Testing.."
dotnet restore /gitrepo/src/Server/Server.csproj"

echo 'Docker container down'
docker compose down

echo 'Docker container up'
docker compose up -d
